[package]
name = "fluence"
version = "0.2.0"  # remember to update html_root_url
description = "Fluence backend SDK for developing backend applications for the Fluence network"
documentation = "https://docs.rs/fluence/"
repository = "https://github.com/fluencelabs/rust-sdk"
authors = ["Fluence Labs"]
readme = "Readme.md"
keywords = ["fluence", "sdk", "webassembly"]
categories = ["api-bindings", "wasm"]
license = "Apache-2.0"

[package.metadata.docs.rs] # https://docs.rs/about
all-features = true

[lib]
path = "src/lib.rs"

[dependencies]
fluence-sdk-macro = { path = "crates/macro", version = "=0.2.0" }
fluence-sdk-main = { path = "crates/main", version = "=0.2.0" }

[features]
# Print some internal logs by log_utf8_string
debug = ["fluence-sdk-main/debug"]

# Print some internal logs by log_utf8_string
logger = ["fluence-sdk-main/logger"]

[workspace]
members = [
  "crates/main",
  "crates/macro",
  "crates/wit",
  ]
