[package]
name = "fluence"
version = "0.2.18"  # remember to update html_root_url
description = "Fluence backend SDK for developing backend applications for the Fluence network"
documentation = "https://docs.rs/fluence/"
repository = "https://github.com/fluencelabs/rust-sdk"
authors = ["Fluence Labs"]
readme = "README.md"
keywords = ["fluence", "sdk", "webassembly"]
categories = ["api-bindings", "wasm"]
license = "Apache-2.0"
edition = "2018"

[package.metadata.docs.rs] # https://docs.rs/about
all-features = true

[lib]
path = "src/lib.rs"

[dependencies]
fluence-sdk-macro = { path = "crates/macro", version = "=0.2.18" }
fluence-sdk-main = { path = "crates/main", version = "=0.2.18" }

[features]
# Print some internal logs by log_utf8_string
debug = ["fluence-sdk-main/debug"]

# Enable logger (this will cause log_utf8_string to appear in imports)
logger = ["fluence-sdk-main/logger"]

[workspace]
members = [
  "crates/main",
  "crates/macro",
  "crates/wit",
  ]
