[workspace]
members = [
  "crates/fce-macro",
  "crates/fce-test-macro",
  "crates/fce-test-macro-impl",
  "crates/main",
  "crates/timestamp-macro",
  "crates/timestamp-macro-impl",
  "crates/wit",
  "fluence",
  "fluence-test"
  ]
