version: 2
jobs:
  marine rs sdk:
    docker:
      - image: circleci/rust:latest
    environment:
      RUST_BACKTRACE: 1
      RUST_TEST_THREADS: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - backendsdk01-{{ checksum "Cargo.toml" }}
      - run: | #TODO: enable 'stable' and 'beta' once `allocator_api` becomes stable
          rustup toolchain install nightly-2021-02-27
          rustup default nightly-2021-02-27
          rustup override set nightly-2021-02-27
          rustup target add wasm32-wasi
          rustup component add rustfmt
          rustup component add clippy

          cargo fmt --all -- --check --color always
          cargo build -v --target wasm32-wasi --all-features
          cargo clippy -v --target wasm32-wasi
          (cd crates/marine-macro-impl; cargo test)

          TARGET=wasm32-wasi cargo test -v --all-features

      - save_cache:
          paths:
            - ~/.cargo
            - ~/.rustup
          key: backendsdk01-{{ checksum "Cargo.toml" }}

workflows:
  version: 2
  marine-rs-sdk:
    jobs:
      - marine rs sdk
