name: "marine-rs-sdk"

on:
  pull_request:
  push:
    branches:
      - "master"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  RUST_TEST_THREADS: 1

jobs:
  marine-rs-sdk:
    name: "Run tests"
    runs-on: builder

    steps:
      - uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo build
        env:
          CARGO_BUILD_TARGET: wasm32-wasi
        run: cargo build

      - name: Run cargo check
        run: cargo check -v --all-features

      - name: Run marine-macro-impl tests
        run: cargo test
        working-directory: crates/marine-macro-impl

      - name: Run cargo test
        run: cargo test --release --all-features --no-fail-fast

      - name: Run cargo clippy
        env:
          CARGO_BUILD_TARGET: wasm32-wasi
        run: cargo clippy
